inherit_gem:
  panolint: panolint-rubocop.yml
Metrics/BlockLength:
  Exclude:
    - scan_left.gemspec
    - spec/*.rb
Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile
    - Rakefile
    - bin/*
