# Reference: https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"

    # Automerge development dependencies.
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
