name: Main
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        # Due to https://github.com/actions/runner/issues/849, we have to use
        # quotes for '3.0'. Without quotes, CI runs 3.1.1, which fails due to
        # https://github.com/rubygems/rubygems/issues/5234 as of 2022-02-28.
        ruby: [ 2.5, 2.6, 2.7, '3.0', jruby ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Use 'bundler-cache: true' instead of actions/cache as advised:
    #   * https://github.com/actions/cache/blob/main/examples.md#ruby---bundler
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rspec

    - run: bundle exec rubocop
      if: matrix.ruby == 3.0
