name: Main
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.5, 2.6, 2.7, 3.0, jruby ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Use 'bundler-cache: true' instead of actions/cache as advised:
    #   * https://github.com/actions/cache/blob/main/examples.md#ruby---bundler
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rspec

    - run: bundle exec rubocop
      if: matrix.ruby == 3.0
